/*
** EPITECH PROJECT, 2021
** main
** File description:
** main
*/

#ifndef MY_SYSCALLS_H_
#define MY_SYSCALLS_H_

typedef enum {
    EMPTY,          /* nothing / void */
    U_INT,          /* unsigned int / size_t ... */
    CHAR_S,         /* char pointer */
    INT,            /* int */
    STRUCT,         /* some kind of structure */
    VP,             /* void pointer */
    U_LONG,         /* unsigned long */
    INT_S,          /* int pointer */
    FP,             /* function pointer */
    CHAR_SS,        /* char pointer to pointer */
    LONG,           /* long */
    ENUM,           /* some kind of enum */
    U_INT_S,        /* unsigned int pointer */
    U_LONG_S,       /* unsigned long pointer */
    VPP,            /* void pointer to pointer */
    UNIMPLEMENTED,  /* if the function is not implemented */
} type_t;

typedef struct {
    const char *name;
    int nb_args;
    int a1;
    int a2;
    int a3;
    int a4;
    int a5;
    int a6;
    int ret;
} syscall_t;

static const syscall_t syscall_table[] = {
    {"read", 3, U_INT, CHAR_S, U_INT, 0, 0, 0, U_INT},
    {"write", 3, U_INT, CHAR_S, U_INT, 0, 0, 0, U_INT},
    {"open", 3, CHAR_S, INT, U_INT, 0, 0, 0, INT},
    {"close", 1, U_INT, 0, 0, 0, 0, 0, INT},
    {"stat", 2, CHAR_S, STRUCT, 0, 0, 0, 0, INT},
    {"fstat", 2, U_INT, STRUCT, 0, 0, 0, 0, INT},
    {"lstat", 2, CHAR_S, STRUCT, 0, 0, 0, 0, INT},
    {"poll", 3, STRUCT, U_INT, INT, 0, 0, 0, INT},
    {"lseek", 3, U_INT, U_INT, U_INT, 0, 0, 0, U_INT},
    {"mmap", 6, VP, U_INT, INT, INT, INT, U_INT, VP},
    {"mprotect", 3, VP, U_INT, INT, 0, 0, 0, INT},
    {"munmap", 2, VP, U_INT, 0, 0, 0, 0, INT},
    {"brk", 1, VP, 0, 0, 0, 0, 0, INT},
    {"rt_sigaction", 3, INT, STRUCT, STRUCT, 0, 0, 0, INT},
    {"rt_sigprocmask", 3, INT, STRUCT, STRUCT, 0, 0, 0, INT},
    {"rt_sigreturn", 1, U_INT, 0, 0, 0, 0, 0, INT},
    {"ioctl", 2, INT, U_LONG, 0, 0, 0, 0, INT},
    {"pread64", 4, INT, VP, U_INT, STRUCT, 0, 0, U_INT},
    {"pwrite64", 4, INT, VP, U_INT, STRUCT, 0, 0, U_INT},
    {"readv", 3, INT, STRUCT, INT, 0, 0, 0, U_INT},
    {"writev", 3, INT, STRUCT, INT, 0, 0, 0, U_INT},
    {"access", 2, CHAR_S, INT, 0, 0, 0, 0, INT},
    {"pipe", 1, INT_S, 0, 0, 0, 0, 0, INT},
    {"select", 5, INT, CHAR_S, CHAR_S, CHAR_S, STRUCT, 0, INT},
    {"sched_yield", 0, 0, 0, 0, 0, 0, 0, INT},
    {"mremap", 4, VP, U_INT, U_INT, INT, 0, 0, VP},
    {"msync", 3, VP, U_INT, INT, 0, 0, 0, INT},
    {"mincore", 3, VP, U_INT, CHAR_S, 0, 0, 0, INT},
    {"madvise", 3, VP, U_INT, INT, 0, 0, 0, INT},
    {"shmget", 3, STRUCT, U_INT, INT, 0, 0, 0, INT},
    {"shmat", 3, INT, VP, INT, 0, 0, 0, VP},
    {"shmctl", 3, INT, INT, STRUCT, 0, 0, 0, INT},
    {"dup", 1, INT, 0, 0, 0, 0, 0, INT},
    {"dup2", 2, INT, INT, 0, 0, 0, 0, INT},
    {"pause", 0, 0, 0, 0, 0, 0, 0, INT},
    {"nanosleep", 2, STRUCT, STRUCT, 0, 0, 0, 0, INT},
    {"getitimer", 2, INT, STRUCT, 0, 0, 0, 0, INT},
    {"alarm", 1, U_INT, 0, 0, 0, 0, 0, U_INT},
    {"setitimer", 3, INT, STRUCT, STRUCT, 0, 0, 0, INT},
    {"getpid", 0, 0, 0, 0, 0, 0, 0, U_INT},
    {"sendfile", 4, INT, INT, U_INT, U_INT, 0, 0, U_INT},
    {"socket", 3, INT, INT, INT, 0, 0, 0, INT},
    {"connect", 3, INT, STRUCT, U_LONG, 0, 0, 0, INT},
    {"accept", 3, INT, STRUCT, U_LONG, 0, 0, 0, INT},
    {"send", 4, INT, VP, U_INT, INT, 0, 0, 0}, /* TODO maybe rename to sendto */
    {"recvfrom", 6, INT, VP, U_INT, INT, STRUCT, U_LONG, U_INT},
    {"sendmsg", 3, INT, STRUCT, INT, 0, 0, 0, U_INT},
    {"recvmsg", 3, INT, STRUCT, INT, 0, 0, 0, U_INT},
    {"shutdown", 2, INT, INT, 0, 0, 0, 0, INT},
    {"bind", 3, INT, STRUCT, U_LONG, 0, 0, 0, INT},
    {"listen", 2, INT, INT, 0, 0, 0, 0, INT},
    {"getsockname", 3, INT, STRUCT, U_LONG, 0, 0, 0, INT},
    {"getpeername", 3, INT, STRUCT, U_LONG, 0, 0, 0, INT},
    {"socketpair", 4, INT, INT, INT, INT_S, 0, 0, INT},
    {"setsockopt", 5, INT, INT, INT, VP, U_LONG, 0, INT},
    {"getsockopt", 5, INT, INT, INT, VP, U_LONG, 0, INT},
    {"clone", 4, FP, VP, INT, VP, 0, 0, INT},
    {"fork", 0, 0, 0, 0, 0, 0, 0, U_INT},
    {"vfork", 0, 0, 0, 0, 0, 0, 0, U_INT},
    {"execve", 3, CHAR_S, CHAR_SS, CHAR_SS, 0, 0, 0, INT},
    {"exit", 1, INT, 0, 0, 0, 0, 0, 0},
    {"wait4", 4, U_INT, INT_S, INT, STRUCT, 0, 0, U_INT},
    {"kill", 2, U_INT, INT, 0, 0, 0, 0, INT},
    {"uname", 1, STRUCT, 0, 0, 0, 0, 0, INT},
    {"semget", 3, U_INT, INT, INT, 0, 0, 0, INT},
    {"semop", 3, INT, STRUCT, U_INT, 0, 0, 0, INT},
    {"semctl", 3, INT, INT, INT, 0, 0, 0, INT},
    {"shmdt", 1, VP, 0, 0, 0, 0, 0, INT},
    {"msgget", 2, U_INT, INT, 0, 0, 0, 0, INT},
    {"msgsnd", 4, INT, VP, U_INT, INT, 0, 0, INT},
    {"msgrcv", 5, INT, VP, U_INT, LONG, INT, 0, U_INT},
    {"msgctl", 3, INT, INT, STRUCT, 0, 0, 0, INT},
    {"fcntl", 2, INT, INT, 0, 0, 0, 0, INT},
    {"flock", 2, INT, INT, 0, 0, 0, 0, INT},
    {"fsync", 1, INT, 0, 0, 0, 0, 0, INT},
    {"fdatasync", 1, INT, 0, 0, 0, 0, 0, INT},
    {"truncate", 2, CHAR_S, U_INT, 0, 0, 0, 0, INT},
    {"ftruncate", 2, INT, U_INT, 0, 0, 0, 0, INT},
    {"getdents", 3, U_INT, STRUCT, U_INT, 0, 0, 0, INT},
    {"getcwd", 2, CHAR_S, U_INT, 0, 0, 0, 0, CHAR_S},
    {"chdir", 1, CHAR_S, 0, 0, 0, 0, 0, INT},
    {"fchdir", 1, INT, 0, 0, 0, 0, 0, INT},
    {"rename", 2, CHAR_S, CHAR_S, 0, 0, 0, 0, INT},
    {"mkdir", 2, CHAR_S, STRUCT, 0, 0, 0, 0, INT},
    {"rmdir", 1, CHAR_S, 0, 0, 0, 0, 0, INT},
    {"creat", 2, CHAR_S, STRUCT, 0, 0, 0, 0, INT},
    {"link", 2, CHAR_S, CHAR_S, 0, 0, 0, 0, INT},
    {"unlink", 1, CHAR_S, 0, 0, 0, 0, 0, INT},
    {"symlink", 2, CHAR_S, CHAR_S, 0, 0, 0, 0, INT},
    {"readlink", 3, CHAR_S, CHAR_S, U_INT, 0, 0, 0, U_INT},
    {"chmod", 2, CHAR_S, STRUCT, 0, 0, 0, 0, INT},
    {"fchmod", 2, INT, STRUCT, 0, 0, 0, 0, INT},
    {"chown", 3, CHAR_S, U_INT, U_INT, 0, 0, 0, INT},
    {"fchown", 3, INT, U_INT, U_INT, 0, 0, 0, INT},
    {"lchown", 3, CHAR_S, U_INT, U_INT, 0, 0, 0, INT},
    {"umask", 1, STRUCT, 0, 0, 0, 0, 0, STRUCT},
    {"gettimeofday", 2, STRUCT, STRUCT, 0, 0, 0, 0, INT},
    {"getrlimit", 2, INT, STRUCT, 0, 0, 0, 0, INT},
    {"getrusage", 2, INT, STRUCT, 0, 0, 0, 0, INT},
    {"sysinfo", 1, STRUCT, 0, 0, 0, 0, 0, INT},
    {"times", 1, STRUCT, 0, 0, 0, 0, 0, STRUCT},
    {"ptrace", 4, ENUM, U_INT, VP, VP, 0, 0, LONG},
    {"getuid", 0, 0, 0, 0, 0, 0, 0, U_INT},
    {"syslog", 3, INT, CHAR_S, INT, 0, 0, 0, INT},
    {"getgid", 0, 0, 0, 0, 0, 0, 0, INT},
    {"setuid", 1, INT, 0, 0, 0, 0, 0, INT},
    {"setgid", 1, INT, 0, 0, 0, 0, 0, INT},
    {"geteuid", 0, 0, 0, 0, 0, 0, 0, INT},
    {"getegid", 0, 0, 0, 0, 0, 0, 0, INT},
    {"setpgid", 2, INT, INT, 0, 0, 0, 0, INT},
    {"getppid", 1, INT, 0, 0, 0, 0, 0, INT},
    {"getpgrp", 0, 0, 0, 0, 0, 0, 0, INT},
    {"setsid", 0, 0, 0, 0, 0, 0, 0, INT},
    {"setreuid", 2, U_INT, U_INT, 0, 0, 0, 0, INT},
    {"setregid", 2, U_INT, U_INT, 0, 0, 0, 0, INT},
    {"getgroups", 2, INT, INT_S, 0, 0, 0, 0, INT},
    {"setgroups", 2, U_INT, INT_S, 0, 0, 0, 0, INT},
    {"setresuid", 3, U_INT, U_INT, U_INT, 0, 0, 0, INT},
    {"getresuid", 3, U_INT_S, U_INT_S, U_INT_S, 0, 0, 0, INT},
    {"setresgid", 3, U_INT, U_INT, U_INT, 0, 0, 0, INT},
    {"getresgid", 3, U_INT_S, U_INT_S, U_INT_S, 0, 0, 0, INT},
    {"getpgid", 1, U_INT, 0, 0, 0, 0, 0, U_INT},
    {"setfsuid", 1, U_INT, 0, 0, 0, 0, 0, INT},
    {"setfsgid", 1, U_INT, 0, 0, 0, 0, 0, INT},
    {"getsid", 1, U_INT, 0, 0, 0, 0, 0, U_INT},
    {"capget", 2, STRUCT, STRUCT, 0, 0, 0, 0, INT},
    {"capset", 2, STRUCT, STRUCT, 0, 0, 0, 0, INT},
    {"rt_sigpending", 1, STRUCT, 0, 0, 0, 0, 0, INT},
    {"rt_sigtimedwait", 3, STRUCT, STRUCT, STRUCT, 0, 0, 0, INT},
    {"rt_sigqueueinfo", 3, U_INT, INT, STRUCT, 0, 0, 0, INT},
    {"rt_sigsuspend", 1, STRUCT, 0, 0, 0, 0, 0, INT},
    {"sigaltstack", 2, STRUCT, STRUCT, 0, 0, 0, 0, INT},
    {"utime", 2, CHAR_S, STRUCT, 0, 0, 0, 0, INT},
    {"mknod", 3, CHAR_S, STRUCT, STRUCT, 0, 0, 0, INT},
    {"uselib", 1, CHAR_S, 0, 0, 0, 0, 0, INT},
    {"personality", 1, U_LONG, 0, 0, 0, 0, 0, INT},
    {"ustat", 2, STRUCT, STRUCT, 0, 0, 0, 0, INT},
    {"statfs", 2, CHAR_S, CHAR_S, 0, 0, 0, 0, INT},
    {"fstatfs", 2, INT, STRUCT, 0, 0, 0, 0, INT},
    {"sysfs", 2, INT, CHAR_S, 0, 0, 0, 0, INT},
    {"getpriority", 2, INT, INT, 0, 0, 0, 0, INT},
    {"setpriority", 3, INT, INT, INT, 0, 0, 0, INT},
    {"sched_setparam", 2, U_INT, STRUCT, 0, 0, 0, 0, INT},
    {"sched_getparam", 2, U_INT, STRUCT, 0, 0, 0, 0, INT},
    {"sched_setscheduler", 3, U_INT, INT, STRUCT, 0, 0, 0, INT},
    {"sched_getscheduler", 1, U_INT, 0, 0, 0, 0, 0, INT},
    {"sched_get_priority_max", 1, INT, 0, 0, 0, 0, 0, INT},
    {"sched_get_priority_min", 1, INT, 0, 0, 0, 0, 0, INT},
    {"sched_rr_get_interval", 2, U_INT, STRUCT, 0, 0, 0, 0, INT},
    {"mlock", 2, VP, U_INT, 0, 0, 0, 0, INT},
    {"munlock", 2, VP, U_INT, 0, 0, 0, 0, INT},
    {"mlockall", 1, INT, 0, 0, 0, 0, 0, INT},
    {"munlockall", 0, 0, 0, 0, 0, 0, 0, INT},
    {"vhangup", 0, 0, 0, 0, 0, 0, 0, INT},
    {"modify_ldt", 3, INT, VP, U_LONG, 0, 0, 0, INT},
    {"pivot_root", 2, CHAR_S, CHAR_S, 0, 0, 0, 0, INT},
    {"_sysctl", 1, STRUCT, 0, 0, 0, 0, 0, INT},
    {"prctl", 5, INT, U_LONG, U_LONG, U_LONG, U_LONG, 0, INT},
    {"arch_prctl", 2, INT, U_LONG, 0, 0, 0, 0, INT},
    {"adjtimex", 1, STRUCT, 0, 0, 0, 0, 0, INT},
    {"setrlimit", 2, INT, STRUCT, 0, 0, 0, 0, INT},
    {"chroot", 1, CHAR_S, 0, 0, 0, 0, 0, INT},
    {"sync", 0, 0, 0, 0, 0, 0, 0, 0},
    {"acct", 1, CHAR_S, 0, 0, 0, 0, 0, INT},
    {"settimeofday", 2, STRUCT, STRUCT, 0, 0, 0, 0, INT},
    {"mount", 5, CHAR_S, CHAR_S, CHAR_S, U_LONG, VP, 0, INT},
    {"umount2", 2, CHAR_S, INT, 0, 0, 0, 0, INT},
    {"swapon", 2, CHAR_S, INT, 0, 0, 0, 0, INT},
    {"swapoff", 1, CHAR_S, 0, 0, 0, 0, 0, INT},
    {"reboot", 4, INT, INT, INT, VP, 0, 0, INT},
    {"sethostname", 2, CHAR_S, U_INT, 0, 0, 0, 0, INT},
    {"setdomainname", 2, CHAR_S, U_INT, 0, 0, 0, 0, INT},
    {"iopl", 1, INT, 0, 0, 0, 0, 0, INT},
    {"ioperm", 3, U_LONG, U_LONG, INT, 0, 0, 0, INT},
    {"create_module", 2, CHAR_S, U_INT, 0, 0, 0, 0, STRUCT},
    {"init_module", 3, VP, U_LONG, CHAR_S, 0, 0, 0, INT},
    {"delete_module", 2, CHAR_S, INT, 0, 0, 0, 0, INT},
    {"get_kernel_syms", 1, STRUCT, 0, 0, 0, 0, 0, INT},
    {"query_module", 5, CHAR_S, INT, VP, U_INT, U_INT, 0, INT},
    {"quotactl", 4, INT, CHAR_S, INT, STRUCT, 0, 0, INT}, /* TODO */
    {"nfsservctl", 3, INT, STRUCT, STRUCT, 0, 0, 0, LONG},
    {"getpmsg", 5, INT, STRUCT, STRUCT, INT_S, INT_S, 0, INT},
    {"putpmsg", 4, INT, STRUCT, STRUCT, INT, 0, 0, INT},
    {"afs_syscall", 0, 0, 0, 0, 0, 0, 0, UNIMPLEMENTED},
    {"tuxcall", 0, 0, 0, 0, 0, 0, 0, UNIMPLEMENTED},
    {"security", 0, 0, 0, 0, 0, 0, 0, UNIMPLEMENTED}, /* TODO */
    {"gettid", 0, 0, 0, 0, 0, 0, 0, U_INT},
    {"readahead", 3, INT, U_LONG, U_INT, 0, 0, 0, U_INT},
    {"setxattr", 5, CHAR_S, CHAR_S, VP, U_INT, INT, 0, INT},
    {"lsetxattr", 5, CHAR_S, CHAR_S, VP, U_INT, INT, 0, INT},
    {"fsetxattr", 5, INT, CHAR_S, VP, U_INT, INT, 0, INT},
    {"getxattr", 4, CHAR_S, CHAR_S, VP, U_INT, 0, 0, U_INT},
    {"lgetxattr", 4, CHAR_S, CHAR_S, VP, U_INT, 0, 0, U_INT},
    {"fgetxattr", 4, INT, CHAR_S, VP, U_INT, 0, 0, U_INT},
    {"listxattr", 3, CHAR_S, CHAR_S, U_INT, 0, 0, 0, U_INT},
    {"llistxattr", 3, CHAR_S, CHAR_S, U_INT, 0, 0, 0, U_INT},
    {"flistxattr", 3, INT, CHAR_S, U_INT, 0, 0, 0, U_INT},
    {"removexattr", 2, CHAR_S, CHAR_S, 0, 0, 0, 0, INT},
    {"lremovexattr", 2, CHAR_S, CHAR_S, 0, 0, 0, 0, INT},
    {"fremovexattr", 2, INT, CHAR_S, 0, 0, 0, 0, INT},
    {"tkill", 2, INT, INT, 0, 0, 0, 0, INT},
    {"time", 1, STRUCT, 0, 0, 0, 0, 0, STRUCT},
    {"futex", 6, INT_S, INT, INT, STRUCT, INT_S, INT, INT},
    {"sched_setaffinity", 3, INT, U_INT, STRUCT, 0, 0, 0, INT},
    {"sched_getaffinity", 3, INT, U_INT, STRUCT, 0, 0, 0, INT},
    {"set_thread_area", 1, STRUCT, 0, 0, 0, 0, 0, INT},
    {"io_setup", 2, U_INT, STRUCT, 0, 0, 0, 0, INT},
    {"io_destroy", 1, STRUCT, 0, 0, 0, 0, 0, INT},
    {"io_getevents", 5, STRUCT, LONG, LONG, STRUCT, STRUCT, 0, INT},
    {"io_submit", 3, STRUCT, LONG, STRUCT, 0, 0, 0, INT},
    {"io_cancel", 3, STRUCT, STRUCT, STRUCT, 0, 0, 0, INT},
    {"get_thread_area", 1, STRUCT, 0, 0, 0, 0, 0, INT},
    {"lookup_dcookie", 3, U_INT, CHAR_S, U_INT, 0, 0, 0, INT},
    {"epoll_create", 1, INT, 0, 0, 0, 0, 0, INT},
    {"epoll_ctl_old", 4, INT, INT, INT, STRUCT, 0, 0, INT},
    {"epoll_wait_old", 4, INT, STRUCT, INT, INT, 0, 0, INT},
    {"remap_file_pages", 5, VP, U_INT, INT, U_INT, INT, 0, INT},
    {"getdents64", 3, INT, VP, U_INT, 0, 0, 0, U_INT},
    {"set_tid_address", 1, INT_S, 0, 0, 0, 0, 0, LONG},
    {"restart_syscall", 0, 0, 0, 0, 0, 0, 0, LONG},
    {"semtimedop", 4, INT, STRUCT, U_INT, STRUCT, 0, 0, INT},
    {"fadvise64", 4, INT, U_LONG, U_LONG, INT, 0, 0, INT},
    {"timer_create", 3, STRUCT, STRUCT, STRUCT, 0, 0, 0, INT},
    {"timer_settime", 4, STRUCT, INT, STRUCT, STRUCT, 0, 0, INT},
    {"timer_gettime", 2, STRUCT, STRUCT, 0, 0, 0, 0, INT},
    {"timer_getoverrun", 1, STRUCT, 0, 0, 0, 0, 0, INT},
    {"timer_delete", 1, STRUCT, 0, 0, 0, 0, 0, INT},
    {"clock_settime", 2, STRUCT, STRUCT, 0, 0, 0, 0, INT},
    {"clock_gettime", 2, STRUCT, STRUCT, 0, 0, 0, 0, INT},
    {"clock_getres", 2, STRUCT, STRUCT, 0, 0, 0, 0, INT},
    {"clock_nanosleep", 4, STRUCT, INT, STRUCT, STRUCT, 0, 0, INT},
    {"exit_group", 1, INT, 0, 0, 0, 0, 0, 0},
    {"epoll_wait", 4, INT, STRUCT, INT, INT, 0, 0, INT},
    {"epoll_ctl", 4, INT, INT, INT, STRUCT, 0, 0, INT},
    {"tgkill", 3, INT, INT, INT, 0, 0, 0, INT},
    {"utimes", 2, CHAR_S, STRUCT, 0, 0, 0, 0, INT},
    {"vserver", 0, 0, 0, 0, 0, 0, 0, UNIMPLEMENTED},
    {"mbind", 6, VP, U_LONG, INT, U_LONG_S, U_LONG, U_INT, LONG},
    {"set_mempolicy", 3, INT, U_LONG_S, U_LONG, 0, 0, 0, LONG},
    {"get_mempolicy", 5, INT_S, U_LONG_S, U_LONG, VP, U_LONG, 0, LONG},
    {"mq_open", 2, CHAR_S, INT, 0, 0, 0, 0, STRUCT},
    {"mq_unlink", 1, CHAR_S, 0, 0, 0, 0, 0, INT},
    {"mq_timesend", 5, STRUCT, CHAR_S, U_INT, U_INT, STRUCT, 0, INT},
    {"mq_timereceive", 4, STRUCT, CHAR_S, U_INT, U_INT, 0, 0, U_INT},
    {"mq_notify", 2, STRUCT, STRUCT, 0, 0, 0, 0, INT},
    {"mq_getsetattr", 3, STRUCT, STRUCT, STRUCT, 0, 0, 0, INT},
    {"kexec_load", 4, U_LONG, U_LONG, STRUCT, U_LONG, 0, 0, LONG},
    {"waitid", 4, STRUCT, STRUCT, STRUCT, INT, 0, 0, INT},
    {"add_key", 5, CHAR_S, CHAR_S, VP, U_INT, STRUCT, 0, STRUCT},
    {"request_key", 4, CHAR_S, CHAR_S, CHAR_S, STRUCT, 0, 0, STRUCT},
    {"keyctl", 1, INT, 0, 0, 0, 0, 0, LONG},
    {"ioprio_set", 3, INT, INT, INT, 0, 0, 0, INT},
    {"ioprio_get", 2, INT, INT, 0, 0, 0, 0, INT},
    {"inotify_init", 0, 0, 0, 0, 0, 0, 0, INT},
    {"inotify_add_watch", 3, INT, CHAR_S, U_INT, 0, 0, 0, INT},
    {"inotify_rm_watch", 2, INT, INT, 0, 0, 0, 0, INT},
    {"migrate_pages", 4, INT, U_LONG, U_LONG_S, U_LONG_S, 0, 0, LONG},
    {"openat", 3, INT, CHAR_S, INT, 0, 0, 0, INT},
    {"mkdirat", 3, INT, CHAR_S, STRUCT, 0, 0, 0, INT},
    {"mknodat", 4, INT, CHAR_S, STRUCT, STRUCT, 0, 0, INT},
    {"fchownat", 5, INT, CHAR_S, STRUCT, STRUCT, INT, 0, INT},
    {"futimesat", 3, INT, CHAR_S, STRUCT, 0, 0, 0, INT},
    {"newfstatat", 4, INT, CHAR_S, STRUCT, INT, 0, 0, INT},
    {"unlinkat", 3, INT, CHAR_S, INT, 0, 0, 0, INT},
    {"renameat", 4, INT, CHAR_S, INT, CHAR_S, 0, 0, INT},
    {"linkat", 5, INT, CHAR_S, INT, CHAR_S, INT, 0, INT},
    {"symlinkat", 3, CHAR_S, INT, CHAR_S, 0, 0, 0, INT},
    {"readlinkat", 4, INT, CHAR_S, CHAR_S, U_INT, 0, 0, U_INT},
    {"fchmodat", 4, INT, CHAR_S, STRUCT, INT, 0, 0, INT},
    {"faccessat", 4, INT, CHAR_S, INT, INT, 0, 0, INT},
    {"pselect6", 6, INT, STRUCT, STRUCT, STRUCT, STRUCT, STRUCT, INT},
    {"ppoll", 4, STRUCT, STRUCT, STRUCT, STRUCT, 0, 0, INT},
    {"unshare", 1, INT, 0, 0, 0, 0, 0, INT},
    {"set_robust_list", 2, STRUCT, INT, 0, 0, 0, 0, LONG},
    {"get_robust_list", 3, INT, STRUCT, U_INT_S, 0, 0, 0, LONG},
    {"splice", 6, INT, STRUCT, INT, STRUCT, U_INT, U_INT, 0},
    {"tee", 4, INT, INT, U_INT, U_INT, 0, 0, 0},
    {"sync_file_range", 4, INT, STRUCT, STRUCT, U_INT, 0, 0, INT},
    {"vmsplice", 4, INT, STRUCT, U_LONG, U_INT, 0, 0, U_INT},
    {"move_pages", 6, INT, U_LONG, VPP, INT_S, INT_S, INT, LONG},
    {"utimensat", 4, INT, CHAR_S, STRUCT, INT, 0, 0, INT},
    {"epoll_pwait", 5, INT, STRUCT, INT, INT, STRUCT, 0, INT},
    {"signalfd", 3, INT, STRUCT, INT, 0, 0, 0, INT},
    {"timerfd_create", 2, INT, INT, 0, 0, 0, 0, INT},
    {"eventfd", 2, U_INT, INT, 0, 0, 0, 0, INT},
    {"fallocate", 4, INT, INT, STRUCT, STRUCT, 0, 0, INT},
    {"timerfd_settime", 4, INT, INT, STRUCT, STRUCT, 0, 0, INT},
    {"timerfd_gettime", 2, INT, STRUCT, 0, 0, 0, 0, INT},
    {"accept4", 3, INT, STRUCT, STRUCT, 0, 0, 0, INT},
    {"signalfd4", 3, INT, STRUCT, INT, 0, 0, 0, INT},
    {"eventfd2", 1, U_INT, 0, 0, 0, 0, 0, INT},
    {"epoll_create1", 0, 0, 0, 0, 0, 0, 0, INT},
    {"dup3", 2, INT, INT, 0, 0, 0, 0, INT},
    {"pipe2", 1, INT_S, 0, 0, 0, 0, 0, INT},
    {"inotify_init1", 0, 0, 0, 0, 0, 0, 0, INT},
    {"preadv", 4, INT, STRUCT, INT, STRUCT, 0, 0, U_INT},
    {"pwritev", 4, INT, STRUCT, INT, STRUCT, 0, 0, U_INT},
    {"rt_tgsigqueueinfo", 0, 0, 0, 0, 0, 0, 0, 0},
    {"perf_event_open", 4, STRUCT, INT, INT, U_INT, 0, 0, INT},
    {"recvmmsg", 4, INT, STRUCT, U_INT, STRUCT, 0, 0, INT},
    {"fanotify_init", 2, U_INT, U_INT, 0, 0, 0, 0, INT},
    {"fanotify_mark", 5, INT, U_INT, U_LONG, INT, CHAR_S, 0, INT},
    {"prlimit64", 4, U_INT, INT, STRUCT, STRUCT, 0, 0, INT},
    {"name_to_handle_at", 5, INT, CHAR_S, STRUCT, INT_S, INT, 0, INT},
    {"open_by_handle_at", 3, INT, STRUCT, INT, 0, 0, 0, INT},
    {"syncfs", 1, INT, 0, 0, 0, 0, 0, INT},
    {"sendmmsg", 4, INT, STRUCT, U_INT, INT, 0, 0, INT},
    {"setns", 2, INT, INT, 0, 0, 0, 0, INT},
    {"getcpu", 3, U_INT_S, U_INT_S, STRUCT, 0, 0, 0, INT},
    {"process_vm_readv", 6, INT, STRUCT, U_LONG, STRUCT, U_LONG, U_LONG, U_INT},
    {"process_vm_writev", 6, INT, STRUCT, U_LONG, STRUCT, U_LONG, U_LONG, \
U_INT},
    {"kcmp", 5, INT, INT, INT, U_LONG, U_LONG, 0, INT},
    {"finit_module", 3, INT, CHAR_S, INT, 0, 0, 0, INT},
};

#endif //MY_SYSCALLS_H_
